AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 1024
      Timeout: 600
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CDS_API_KEY: bb3623cd-e4e6-49f6-bb17-6f1b77554a5b